2018-12-25 Tuesday 09:26:32  remote_connection.py : INFO  Could not connect to port 4723 on host localhost
2018-12-25 Tuesday 09:26:32  remote_connection.py : INFO  Could not get IP address for host: localhost
2018-12-25 Tuesday 09:26:32  remote_connection.py : DEBUG  POST http://localhost:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "Android", "appium:platformVersion": "5.1", "appium:deviceName": "HUAWEI TAG-AL00", "appium:appPackage": "com.hanweiyx.hanwei", "appium:appActivity": ".activity.SplashActivity", "appium:unicodeKeyboard": true, "appium:resetKeyboard": true, "appium:noReset": true}]}, "desiredCapabilities": {"platformName": "Android", "platformVersion": "5.1", "deviceName": "HUAWEI TAG-AL00", "appPackage": "com.hanweiyx.hanwei", "appActivity": ".activity.SplashActivity", "unicodeKeyboard": true, "resetKeyboard": true, "noReset": true}}
2018-12-25 Tuesday 09:26:32  connectionpool.py : DEBUG  Starting new HTTP connection (1): localhost:4723
2018-12-25 Tuesday 09:26:32  retry.py : DEBUG  Incremented Retry for (url='/wd/hub/session'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2018-12-25 Tuesday 09:26:32  connectionpool.py : WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1055bd9b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
2018-12-25 Tuesday 09:26:32  connectionpool.py : DEBUG  Starting new HTTP connection (2): localhost:4723
2018-12-25 Tuesday 09:26:32  retry.py : DEBUG  Incremented Retry for (url='/wd/hub/session'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2018-12-25 Tuesday 09:26:32  connectionpool.py : WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1055bda58>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
2018-12-25 Tuesday 09:26:32  connectionpool.py : DEBUG  Starting new HTTP connection (3): localhost:4723
2018-12-25 Tuesday 09:26:32  retry.py : DEBUG  Incremented Retry for (url='/wd/hub/session'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2018-12-25 Tuesday 09:26:32  connectionpool.py : WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1055bdb38>: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session
2018-12-25 Tuesday 09:26:32  connectionpool.py : DEBUG  Starting new HTTP connection (4): localhost:4723
